import type { INodeProperties } from 'n8n-workflow';

const parameters: INodeProperties[] = [];

//
// Timeline Settings
//
parameters.push({
	displayName: 'Background',
	name: 'background',
	type: 'string',
	default: '#000000',
	description: 'Timeline background color (hex format)',
	displayOptions: { show: { operation: ['compileTimeline'] } },
});

parameters.push({
	displayName: 'Resolution',
	name: 'resolution',
	type: 'options',
	default: '1920x1080',
	description: 'Output video resolution',
	displayOptions: { show: { operation: ['compileTimeline'] } },
	options: [
		{ name: '4K (3840x2160)', value: '3840x2160' },
		{ name: '1080p (1920x1080)', value: '1920x1080' },
		{ name: '720p (1280x720)', value: '1280x720' },
		{ name: '480p (854x480)', value: '854x480' },
		{ name: '360p (640x360)', value: '640x360' },
	],
});

//
// Tracks - The main container for clips
//
parameters.push({
	displayName: 'Tracks',
	name: 'tracks',
	type: 'fixedCollection',
	typeOptions: { multipleValues: true },
	default: {},
	displayOptions: { show: { operation: ['compileTimeline'] } },
	description: 'Tracks contain clips. Multiple tracks allow layering (higher z_index renders on top).',
	options: [
		{
			name: 'track',
			displayName: 'Add Track',
			values: [
				{
					displayName: 'Track Z-Index',
					name: 'z_index',
					type: 'number',
					default: 0,
					description: 'Layer order - higher values render on top',
				},
				{
					displayName: 'Clips',
					name: 'clips',
					type: 'fixedCollection',
					typeOptions: { multipleValues: true },
					default: {},
					description: 'Clips in this track',
					options: [
						{
							name: 'clip',
							displayName: 'Add Clip',
							values: [
								// TrackItem: start time
								{
									displayName: 'Start (S)',
									name: 'start',
									type: 'number',
									required: true,
									default: 0,
									description: 'When this clip starts on the timeline (seconds)',
								},
								// Asset Type Selection
								{
									displayName: 'Asset Type',
									name: 'asset_type',
									type: 'options',
									required: true,
									default: 'video',
									options: [
										{ name: 'Video', value: 'video' },
										{ name: 'Audio', value: 'audio' },
										{ name: 'Image', value: 'image' },
										{ name: 'Text', value: 'text' },
										{ name: 'Caption', value: 'caption' },
									],
								},
								// Clip Duration
								{
									displayName: 'Duration (S)',
									name: 'duration',
									type: 'number',
									default: 0,
									description: 'Clip duration in seconds (0 = use asset duration)',
								},
								// ========== VIDEO ASSET ==========
								{
									displayName: 'Video Asset ID',
									name: 'video_asset_id',
									type: 'string',
									default: '',
									description: 'VideoDB video asset ID (e.g., m-12345)',
									displayOptions: { show: { asset_type: ['video'] } },
								},
								{
									displayName: 'Video Start (S)',
									name: 'video_start',
									type: 'number',
									default: 0,
									description: 'Start time within the video asset',
									displayOptions: { show: { asset_type: ['video'] } },
								},
								{
									displayName: 'Video End (S)',
									name: 'video_end',
									type: 'number',
									default: 0,
									description: 'End time within the video asset (0 = full length)',
									displayOptions: { show: { asset_type: ['video'] } },
								},
								// ========== AUDIO ASSET ==========
								{
									displayName: 'Audio Asset ID',
									name: 'audio_asset_id',
									type: 'string',
									default: '',
									description: 'VideoDB audio asset ID (e.g., a-12345)',
									displayOptions: { show: { asset_type: ['audio'] } },
								},
								{
									displayName: 'Audio Start (S)',
									name: 'audio_start',
									type: 'number',
									default: 0,
									description: 'Start time within the audio asset',
									displayOptions: { show: { asset_type: ['audio'] } },
								},
								{
									displayName: 'Audio End (S)',
									name: 'audio_end',
									type: 'number',
									default: 0,
									description: 'End time within the audio asset (0 = full length)',
									displayOptions: { show: { asset_type: ['audio'] } },
								},
								{
									displayName: 'Disable Other Tracks',
									name: 'audio_disable_other_tracks',
									type: 'boolean',
									default: false,
									description: 'Whether to mute other audio while this plays',
									displayOptions: { show: { asset_type: ['audio'] } },
								},
								{
									displayName: 'Fade In (S)',
									name: 'audio_fade_in',
									type: 'number',
									default: 0,
									description: 'Fade in duration (max 5s)',
									displayOptions: { show: { asset_type: ['audio'] } },
								},
								{
									displayName: 'Fade Out (S)',
									name: 'audio_fade_out',
									type: 'number',
									default: 0,
									description: 'Fade out duration (max 5s)',
									displayOptions: { show: { asset_type: ['audio'] } },
								},
								// ========== IMAGE ASSET ==========
								{
									displayName: 'Image Asset ID',
									name: 'image_asset_id',
									type: 'string',
									default: '',
									description: 'VideoDB image asset ID (e.g., img-12345)',
									displayOptions: { show: { asset_type: ['image'] } },
								},
								{
									displayName: 'Image Width',
									name: 'image_width',
									type: 'string',
									default: '100%',
									description: 'Width in pixels or percentage',
									displayOptions: { show: { asset_type: ['image'] } },
								},
								{
									displayName: 'Image Height',
									name: 'image_height',
									type: 'string',
									default: '100%',
									description: 'Height in pixels or percentage',
									displayOptions: { show: { asset_type: ['image'] } },
								},
								{
									displayName: 'Image X',
									name: 'image_x',
									type: 'string',
									default: '0',
									description: 'X position',
									displayOptions: { show: { asset_type: ['image'] } },
								},
								{
									displayName: 'Image Y',
									name: 'image_y',
									type: 'string',
									default: '0',
									description: 'Y position',
									displayOptions: { show: { asset_type: ['image'] } },
								},
								// ========== TEXT ASSET ==========
								{
									displayName: 'Text',
									name: 'text_content',
									type: 'string',
									default: '',
									description: 'Text to display',
									displayOptions: { show: { asset_type: ['text'] } },
								},
								{
									displayName: 'Text Style',
									name: 'text_style',
									type: 'json',
									default: '{}',
									description: 'Text style as JSON object (font, fontsize, fontcolor, x, y, etc.)',
									displayOptions: { show: { asset_type: ['text'] } },
								},
								// ========== CAPTION ASSET ==========
								{
									displayName: 'Caption Source',
									name: 'caption_src',
									type: 'json',
									default: '"auto"',
									description: 'Use "auto" for video transcript or provide transcript JSON array [{start, end, text}, ...]',
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Animation',
									name: 'caption_animation',
									type: 'options',
									default: '',
									displayOptions: { show: { asset_type: ['caption'] } },
									options: [
										{ name: 'None', value: '' },
										{ name: 'Box Highlight', value: 'box_highlight' },
										{ name: 'Color Highlight', value: 'color_highlight' },
										{ name: 'Reveal', value: 'reveal' },
										{ name: 'Karaoke', value: 'karaoke' },
										{ name: 'Impact', value: 'impact' },
										{ name: 'Supersize', value: 'supersize' },
									],
								},
								{
									displayName: 'Caption Font Name',
									name: 'caption_font_name',
									type: 'string',
									default: 'Clear Sans',
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Font Size',
									name: 'caption_font_size',
									type: 'number',
									default: 30,
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Font Bold',
									name: 'caption_font_bold',
									type: 'boolean',
									default: false,
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Font Italic',
									name: 'caption_font_italic',
									type: 'boolean',
									default: false,
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Primary Color',
									name: 'caption_primary_color',
									type: 'string',
									default: '&H00FFFFFF',
									description: 'Primary text color in ASS format',
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Secondary Color',
									name: 'caption_secondary_color',
									type: 'string',
									default: '&H000000FF',
									description: 'Secondary color in ASS format',
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Back Color',
									name: 'caption_back_color',
									type: 'string',
									default: '&H00000000',
									description: 'Background color in ASS format',
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Border Style',
									name: 'caption_border_style',
									type: 'options',
									default: 'outline_and_shadow',
									displayOptions: { show: { asset_type: ['caption'] } },
									options: [
										{ name: 'Outline and Shadow', value: 'outline_and_shadow' },
										{ name: 'Opaque Box', value: 'opaque_box' },
									],
								},
								{
									displayName: 'Caption Outline Width',
									name: 'caption_outline',
									type: 'number',
									default: 1,
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Outline Color',
									name: 'caption_outline_color',
									type: 'string',
									default: '&H00000000',
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Shadow',
									name: 'caption_shadow',
									type: 'number',
									default: 0,
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Alignment',
									name: 'caption_alignment',
									type: 'options',
									default: 'bottom_center',
									displayOptions: { show: { asset_type: ['caption'] } },
									options: [
										{ name: 'Bottom Left', value: 'bottom_left' },
										{ name: 'Bottom Center', value: 'bottom_center' },
										{ name: 'Bottom Right', value: 'bottom_right' },
										{ name: 'Middle Left', value: 'middle_left' },
										{ name: 'Middle Center', value: 'middle_center' },
										{ name: 'Middle Right', value: 'middle_right' },
										{ name: 'Top Left', value: 'top_left' },
										{ name: 'Top Center', value: 'top_center' },
										{ name: 'Top Right', value: 'top_right' },
									],
								},
								{
									displayName: 'Caption Margin Left',
									name: 'caption_margin_l',
									type: 'number',
									default: 30,
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Margin Right',
									name: 'caption_margin_r',
									type: 'number',
									default: 30,
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								{
									displayName: 'Caption Margin Vertical',
									name: 'caption_margin_v',
									type: 'number',
									default: 30,
									displayOptions: { show: { asset_type: ['caption'] } },
								},
								// ========== CLIP PROPERTIES (Common to all assets) ==========
								{
									displayName: 'Clip Scale',
									name: 'clip_scale',
									type: 'number',
									default: 1,
									description: 'Scale factor for the clip',
								},
								{
									displayName: 'Clip Opacity',
									name: 'clip_opacity',
									type: 'number',
									default: 1,
									description: 'Opacity (0-1)',
								},
								{
									displayName: 'Clip Fit',
									name: 'clip_fit',
									type: 'options',
									default: 'crop',
									options: [
										{ name: 'Crop', value: 'crop' },
										{ name: 'Cover', value: 'cover' },
										{ name: 'Contain', value: 'contain' },
										{ name: 'None', value: 'none' },
									],
								},
								{
									displayName: 'Clip Position',
									name: 'clip_position',
									type: 'options',
									default: 'center',
									options: [
										{ name: 'Center', value: 'center' },
										{ name: 'Top', value: 'top' },
										{ name: 'Bottom', value: 'bottom' },
										{ name: 'Left', value: 'left' },
										{ name: 'Right', value: 'right' },
										{ name: 'Top Left', value: 'top-left' },
										{ name: 'Top Right', value: 'top-right' },
										{ name: 'Bottom Left', value: 'bottom-left' },
										{ name: 'Bottom Right', value: 'bottom-right' },
									],
								},
								{
									displayName: 'Clip Offset X',
									name: 'clip_offset_x',
									type: 'number',
									default: 0,
									description: 'Horizontal offset in pixels',
								},
								{
									displayName: 'Clip Offset Y',
									name: 'clip_offset_y',
									type: 'number',
									default: 0,
									description: 'Vertical offset in pixels',
								},
								{
									displayName: 'Clip Z-Index',
									name: 'clip_z_index',
									type: 'number',
									default: 0,
									description: 'Layer order within the track',
								},
								{
									displayName: 'Clip Effect',
									name: 'clip_effect',
									type: 'string',
									default: '',
									description: 'Optional effect to apply',
								},
								{
									displayName: 'Clip Filter',
									name: 'clip_filter',
									type: 'options',
									default: '',
									options: [
										{ name: 'None', value: '' },
										{ name: 'Grayscale', value: 'grayscale' },
										{ name: 'Sepia', value: 'sepia' },
										{ name: 'Invert', value: 'invert' },
										{ name: 'Saturate', value: 'saturate' },
									],
								},
								// Transition
								{
									displayName: 'Transition Type',
									name: 'transition_type',
									type: 'options',
									default: '',
									options: [
										{ name: 'None', value: '' },
										{ name: 'Fade', value: 'fade' },
										{ name: 'Slide Left', value: 'slideLeft' },
										{ name: 'Slide Right', value: 'slideRight' },
										{ name: 'Slide Up', value: 'slideUp' },
										{ name: 'Slide Down', value: 'slideDown' },
									],
								},
								{
									displayName: 'Transition Duration (S)',
									name: 'transition_duration',
									type: 'number',
									default: 0.5,
									displayOptions: { show: { transition_type: ['fade', 'slideLeft', 'slideRight', 'slideUp', 'slideDown'] } },
								},
							],
						},
					],
				},
			],
		},
	],
});

export default parameters;
